CREATE TABLE [dbo].[UserConfig] (
    [Id]                                       INT           NOT NULL,
    [NotificationTitleFontFamily]              NVARCHAR (50) NULL,
    [NotificationTitleHeight]                  INT           NULL,
    [NotificationTitleFontSize]                INT           NULL,
    [NotificationTitleForeground]              NVARCHAR (50) NULL,
    [NotificationTitleBackground]              NVARCHAR (50) NULL,
    [NotificationPanelFontSize]                INT           NULL,
    [NotificationPanelFontFamily]              NVARCHAR (50) NULL,
    [NotificationPanelForeground]              NVARCHAR (50) NULL,
    [NotificationPanelBackground]              NVARCHAR (50) NULL,
    [NotificationPanelHeight]                  INT           NULL,
    [NotificationPanelMargin]                  INT           NULL,
    [NotificationPanelVerticalAlignment]       CHAR (1)      NULL,
    [NotificationPanelTitleVisibility]         CHAR (1)      NULL,
    [NotificationAnimationMode]                CHAR (1)      NULL,
    [NotificationAnimationSpeed]               INT           NULL,
    [QuranTitleFontFamily]                     NVARCHAR (50) NULL,
    [QuranTitleHeight]                         INT           NULL,
    [QuranTitleFontSize]                       INT           NULL,
    [QuranTitleForeground]                     NVARCHAR (50) NULL,
    [QuranTitleBackground]                     NVARCHAR (50) NULL,
    [QuranTitleStrokeColor]                    NVARCHAR (50) NULL,
    [QuranTitleStrokeSize]                     INT           NULL,
    [QuranPanelFontSize]                       INT           NULL,
    [QuranPanelFontFamily]                     NVARCHAR (50) NULL,
    [QuranPanelForeground]                     NVARCHAR (50) NULL,
    [QuranPanelBackground]                     NVARCHAR (50) NULL,
    [QuranPanelStrokeColor]                    NVARCHAR (50) NULL,
    [QuranPanelStrokeSize]                     INT           NULL,
    [QuranPanelHeight]                         INT           NULL,
    [QuranPanelMargin]                         INT           NULL,
    [QuranPanelVerticalAlignment]              CHAR (1)      NULL,
    [QuranPanelTitleVisibility]                CHAR (1)      NULL,
    [QuranAnimationMode]                       VARCHAR (10)  DEFAULT ('Continuous') NULL,
    [QuranAnimationSpeed]                      NVARCHAR (50) NULL,
    [QuranPageNumber]                          INT           NULL,
    [MafatihTitleFontFamily]                   NVARCHAR (50) NULL,
    [MafatihTitleHeight]                       INT           NULL,
    [MafatihTitleFontSize]                     INT           NULL,
    [MafatihTitleForeground]                   NVARCHAR (50) NULL,
    [MafatihTitleBackground]                   NVARCHAR (50) NULL,
    [MafatihTitleStrokeColor]                  NVARCHAR (50) NULL,
    [MafatihTitleStrokeSize]                   INT           NULL,
    [MafatihPanelFontFamily]                   NVARCHAR (50) NULL,
    [MafatihPanelFontSize]                     INT           NULL,
    [MafatihPanelForeground]                   NVARCHAR (50) NULL,
    [MafatihPanelBackground]                   NVARCHAR (50) NULL,
    [MafatihPanelStrokeColor]                  NVARCHAR (50) NULL,
    [MafatihPanelStrokeSize]                   INT           NULL,
    [MafatihPanelHeight]                       INT           NULL,
    [MafatihPanelMargin]                       INT           NULL,
    [MafatihPanelVerticalAlignment]            CHAR (1)      NULL,
    [MafatihPanelTitleVisibility]              CHAR (1)      NULL,
    [MafatihAnimationMode]                     VARCHAR (10)  NULL,
    [MafatihAnimationSpeed]                    INT           NULL,
    [QuranTranslationTitleForeground]          NVARCHAR (50) NULL,
    [QuranTranslationTitleBackground]          NVARCHAR (50) NULL,
    [QuranTranslationTitleFontFamily]          NVARCHAR (50) NULL,
    [QuranTranslationTitleFontSize]            INT           NULL,
    [QuranTranslationTitleHeight]              INT           NULL,
    [QuranTranslationPanelTitleVisibility]     CHAR (1)      NULL,
    [QuranTranslationPanelForeground]          NVARCHAR (50) NULL,
    [QuranTranslationPanelBackground]          NVARCHAR (50) NULL,
    [QuranTranslationPanelFontFamily]          NVARCHAR (50) NULL,
    [QuranTranslationPanelFontSize]            INT           NULL,
    [QuranTranslationPanelHeight]              INT           NULL,
    [QuranTranslationPanelMargin]              INT           NULL,
    [QuranTranslationPanelVerticalAlignment]   CHAR (1)      NULL,
    [QuranTranslationAnimationMode]            NVARCHAR (50) NULL,
    [QuranTranslationAnimationSpeed]           INT           NULL,
    [MafatihTranslationTitleForeground]        NVARCHAR (50) NULL,
    [MafatihTranslationTitleBackground]        NVARCHAR (50) NULL,
    [MafatihTranslationTitleFontFamily]        NVARCHAR (50) NULL,
    [MafatihTranslationTitleFontSize]          INT           NULL,
    [MafatihTranslationTitleHeight]            INT           NULL,
    [MafatihTranslationPanelTitleVisibility]   CHAR (1)      NULL,
    [MafatihTranslationPanelForeground]        NVARCHAR (50) NULL,
    [MafatihTranslationPanelBackground]        NVARCHAR (50) NULL,
    [MafatihTranslationPanelFontFamily]        NVARCHAR (50) NULL,
    [MafatihTranslationPanelFontSize]          INT           NULL,
    [MafatihTranslationPanelHeight]            INT           NULL,
    [MafatihTranslationPanelMargin]            INT           NULL,
    [MafatihTranslationPanelVerticalAlignment] CHAR (1)      NULL,
    [MafatihTranslationAnimationMode]          NVARCHAR (50) NULL,
    [MafatihTranslationAnimationSpeed]         INT           NULL,
    [ControllerMonitorIndex]                   INT           NULL,
    [OutputMonitorIndex]                       INT           NULL,
    [ScreenSaverImageLocation]                 NVARCHAR (50) NULL,
    [PanelImageLocation]                       NVARCHAR (50) NULL,
    [CameraShowStatus]                         CHAR (1)      NULL,
    [DefaultCameraName]                        NVARCHAR (50) NULL,
    [CompanyName]                              NVARCHAR (50) NULL,
    [ScreenSaver]                              CHAR (1)      NULL,
    [LogoStart]                                CHAR (1)      NULL,
    [PortNumber]                               INT           DEFAULT ((5000)) NOT NULL,
    [IsListenerAutoStart]                      CHAR (1)      NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);





